// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJvBLUmWDHbpZuCVbc_z1KD52a_zCNjmA',
    appId: '1:918021310186:web:72e4b59d985ff5c4c33993',
    messagingSenderId: '918021310186',
    projectId: 'sanaa-fcm-app',
    authDomain: 'sanaa-fcm-app.firebaseapp.com',
    storageBucket: 'sanaa-fcm-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrPJDM8b3x3mLoIA_nLZltAFDlbk5pm7g',
    appId: '1:918021310186:android:946aae14b9910f42c33993',
    messagingSenderId: '918021310186',
    projectId: 'sanaa-fcm-app',
    storageBucket: 'sanaa-fcm-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSxcP2_dbPZ5rBbK0AVo9GGxy-cIibc-w',
    appId: '1:918021310186:ios:739f39a49c8f35f8c33993',
    messagingSenderId: '918021310186',
    projectId: 'sanaa-fcm-app',
    storageBucket: 'sanaa-fcm-app.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSxcP2_dbPZ5rBbK0AVo9GGxy-cIibc-w',
    appId: '1:918021310186:ios:739f39a49c8f35f8c33993',
    messagingSenderId: '918021310186',
    projectId: 'sanaa-fcm-app',
    storageBucket: 'sanaa-fcm-app.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJvBLUmWDHbpZuCVbc_z1KD52a_zCNjmA',
    appId: '1:918021310186:web:d3e3e77aef2b3360c33993',
    messagingSenderId: '918021310186',
    projectId: 'sanaa-fcm-app',
    authDomain: 'sanaa-fcm-app.firebaseapp.com',
    storageBucket: 'sanaa-fcm-app.firebasestorage.app',
  );
}
